### ISSUE TITLE
Invalid URL when redirected

### ISSUE THREAD

**Issue by Roosteridk** [jd1378/deno-another-cookiejar#16]
There seems to be an issue with redirects after [v5.0.0](https://github.com/jd1378/deno-another-cookiejar/releases/tag/v5.0.0) where I get an invalid URL error for a redirected request.
```ts
import { wrapFetch } from "https://deno.land/x/another_cookiejar@v5.0.2/mod.ts";

const fetch = wrapFetch();
fetch("https://eksisozluk.com/deno"); // Redirects to https://eksisozluk.com/deno--89984

```
```
error: Uncaught (in promise) TypeError: Invalid URL: '/deno--89984'
  const orig = new URL(original).hostname;
               ^
    at getSerialization (internal:deno_url/00_url.js:74:11)
    at opUrlParse (internal:deno_url/00_url.js:65:10)
    at new URL (internal:deno_url/00_url.js:363:27)
    at isDomainOrSubdomain (https://deno.land/x/another_cookiejar@v5.0.2/fetch_wrapper.ts:25:16)
    at wrappedFetch (https://deno.land/x/another_cookiejar@v5.0.2/fetch_wrapper.ts:123:10)
```

However, using v4.1.5 works just fine.

**Comment by jd1378** [comment]
thanks for reporting this
I have [released a fix](https://github.com/jd1378/deno-another-cookiejar/releases/tag/v5.0.3) and added a test for it
